### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by wiseman** [pylon/streamp3#4]
I've done `brew install lame`, but `pip install streamp3` results in this:
```
  clang: error: no such file or directory: 'lame/hip.c'
  clang: error: no input files
  error: command 'clang' failed with exit status 1
```

**Comment by brentspell** [comment]
I was able to reproduce this issue in a new virtualenv without cython installed. Streamp3 requires cython in order to build. Would you verify that running `pip install cython` allows you to run `pip install streamp3` successfully?

**Comment by brentspell** [comment]
The package should now be installable from an empty virtualenv. Please open a new issue if this is still a problem.
